version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: oms-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: order-management
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - oms-network

  # Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: backend-dev
    container_name: oms-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/order-management?authSource=admin
      - PORT=3000
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    depends_on:
      - mongodb
    networks:
      - oms-network

  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: frontend-dev
    container_name: oms-frontend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - VITE_API_URL=http://localhost:3000/api
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    depends_on:
      - backend
    networks:
      - oms-network

volumes:
  mongodb_data:

networks:
  oms-network:
    driver: bridge
